STOP_MESSAGE = "__STOP__"

CIRCUIT_MOD_DIR = "mod"
CIRCUIT_SIMULATION_CONFIG_NAME = "simulation_config.json"
CIRCUIT_CONFIG_NAME = "circuit_config.json"

SINGLE_NEURON_MOD_DIR = "mechanisms"
SINGLE_NEURON_HOC_DIR = "hoc"
SINGLE_NEURON_MORPHOLOGY_DIR = "morphology"

LIBNRNMECH_PATH = "x86_64/lib/nrnmech.so"

READY_MARKER_FILE_NAME = ".ready"
DIR_LOCK_FILE_NAME = ".dir-lock"

SKELETONIZATION_OUTPUT_ROLE_NAME = "data modeling role"
SKELETONIZATION_OUTPUT_LICENSE_LABEL = "CC BY-NC-SA 4.0 Deed"
