STOP_MESSAGE = "__STOP__"

DEFAULT_CIRCUIT_ID = "dcfa7322-e935-41fa-9807-b1b185f110fc"

CIRCUIT_MOD_FOLDER = "mod"

DEFAULT_CIRCUIT_SIMULATION_CONFIG_NAME = "simulation_config.json"

DEFAULT_CIRCUIT_CONFIG_NAME = "circuit_config.json"

DEFAULT_LIBNRNMECH_PATH = "x86_64/lib/nrnmech.so"
