name: Build and publish staging Docker images for the new distributed archhitecture

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Standard permission for GitHub Actions

on:
  push:
    branches:
      - feat/small-circuit-simulations

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-to-aws-ecr:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: "prod"
      IMAGE_NAME: ${{ vars.PUBLICECR_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up QEMU for ARM emulation
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PUBLICECR_UPLOAD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PUBLICECR_UPLOAD_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.PUBLICECR_REGION }}

      - name: Authenticate with AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and publish the Docker images to AWS ECR
        run: make publish

      # - name: Build and push ARM64 api image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: Dockerfile.api
      #     platforms: linux/arm64
      #     push: true
      #     tags: ${{ vars.PUBLICECR_URI }}:api-staging

      # - name: Build and push AMD64 worker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: Dockerfile.worker
      #     platforms: linux/amd64
      #     push: true
      #     tags: ${{ vars.PUBLICECR_URI }}:worker-staging
