name: Build and publish Docker images for the new distributed archhitecture

permissions:
  id-token: write # Required for OIDC authentication
  contents: write

on:
  push:
    branches:
      - feat/small-circuit-simulations

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-to-aws-ecr:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: "prod"
      IMAGE_NAME: ${{ vars.PUBLICECR_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine new tag
        id: tag
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          DAY=$(date +'%d')
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E "^${YEAR}\.${MONTH}\.${DAY}\.[0-9]+$" | head -n 1 || echo "")

          if [[ -z "$LATEST_TAG" ]]; then
            COUNTER=1
          else
            COUNTER=$(( ${LATEST_TAG##*.} + 1 ))
          fi

          NEW_TAG="${YEAR}.${MONTH}.${DAY}.${COUNTER}"
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG"

      - name: Create Git Tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PUBLICECR_UPLOAD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PUBLICECR_UPLOAD_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.PUBLICECR_REGION }}

      - name: Authenticate with AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and publish the Docker images to AWS ECR
        env:
          IMAGE_TAG_SUFFIX: $NEW_TAG
        run: make publish
